name: Linux binary

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build-stack-${{ hashFiles('**/stack.yaml') }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-build-stack-${{ hashFiles('**/stack.yaml') }}
            ${{ runner.os }}-build-stack-
      - name: Increase swap
        run: |
          free -h

          sudo swapoff /mnt/swapfile
          sudo fallocate -l 13G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile

          free -h

      - name: Build
        run: |
          stack build --ghc-options=-O3 --local-bin-path comparest-linux --copy-bins --flag comparest:Static
      - name: Test
        run: stack test --ghc-options=-O3 --flag comparest:Static --test-arguments='--hide-successes --no-create'

      - name: Zip
        if: github.ref == 'refs/heads/master'
        run: |
          zip comparest-linux comparest-linux/comparest
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/master'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Pre-Release"
          files: |
            *.zip
  comparest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.
        with:
          old: test/golden/common/property-removed/a.yaml
          new: test/golden/common/property-removed/b.yaml
          project_name: Test project
